#!/usr/bin/env bash

# Automatically push branches on commit. Doesn't push in detached head,
# or if the branch name ends in "_local".
# @see https://stackoverflow.com/questions/7925850/how-to-automatically-push-after-committing-in-git#7925891

branch_name=`git symbolic-ref --short HEAD` 
retcode=$?
non_push_suffix="_local"


# Only push if branch_name was found (my be empty if in detached head state)
if [ $retcode = 0 ] ; then
    #Only push if branch_name does not end with the non-push suffix
    if [[ $branch_name != *$non_push_suffix ]] ; then
        echo
        echo "**** Pushing current branch $branch_name to origin"
        echo
        git push origin $branch_name;
    fi
fi
